apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
  namespace: k8s-voteapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        image: chidhvilas/api:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/langdb?replicaSet=rs0"
        - name: CORS_ORIGINS
          value: "http://<frontend-external-ip>,http://example.com"
        - name: PORT
          value: "8080"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
                name: mongodb-secret
                key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
                name: mongodb-secret
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: go-backend-service
  namespace: k8s-voteapp
spec:
  selector:
    app: go-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
