apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
  namespace: k8s-voteapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        image: chidhvilas/api:v2
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/langdb?replicaSet=rs0"
---
apiVersion: v1
kind: Service
metadata:
  name: go-backend-service
  namespace: k8s-voteapp
spec:
  selector:
    app: go-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
